
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uthhjzxobyeecgalnlyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0aGhqenhvYnllZWNnYWxubHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDY5NTEsImV4cCI6MjA1OTk4Mjk1MX0.OWarT7flRR_SWTfqEoQ-yqAI4zodOQ6_eNPaW2c0KX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
  }
});
